# Generated by Django 5.1.1 on 2024-10-01 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_barber_emergencycontactname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='emergencyContactName',
            field=models.CharField(help_text='Enter the full name of the emergency contact.', max_length=100, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='emergencyContactPhoneNumber',
            field=models.CharField(help_text='Enter a valid phone number for the emergency contact. Include country code if necessary.', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter a valid phone number. Include the country code if necessary.')], verbose_name='Emergency Contact Phone Number'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='emergencyContactRelationship',
            field=models.CharField(help_text='Specify the relationship of the emergency contact to the barber (e.g., parent, sibling, friend).', max_length=100, null=True, verbose_name='Emergency Contact Relationship'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='socialInsuranceNumber',
            field=models.CharField(help_text='Enter the 9-digit Social Insurance Number (SIN) without spaces or dashes.', max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'The Social Insurance Number must be exactly 9 digits.')], verbose_name='Social Insurance Number (SIN)'),
        ),
    ]
