# Generated by Django 5.1.1 on 2024-10-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_service_durationtime_alter_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(help_text='Enter Service Duration in Minutes', verbose_name='Service Duration'),
        ),
    ]
