# Generated by Django 5.1.1 on 2024-10-01 12:45

import api.models.validations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberqualification',
            name='user',
            field=models.ForeignKey(help_text='The barber associated with this qualification.', on_delete=django.db.models.deletion.CASCADE, to='api.barber', verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(help_text='Enter Service Duration in Minutes', validators=[
                api.models.validations.validate_duration], verbose_name='Service Duration'),
        ),
    ]
