# Generated by Django 5.1.1 on 2024-10-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_barberqualification_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarberQualification',
        ),
    ]
