# Generated by Django 5.1.1 on 2024-10-01 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_barberqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service', verbose_name='Service Name')),
                ('user', models.ForeignKey(help_text='The barber associated with this qualification.', on_delete=django.db.models.deletion.CASCADE, to='api.barber', verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Barber Qualification',
                'verbose_name_plural': 'Barber Qualifications',
                'constraints': [models.UniqueConstraint(fields=('user', 'service'), name='unique_barber_service')],
            },
        ),
    ]
