# Generated by Django 5.1.1 on 2024-10-01 14:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_barberqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')])),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.barber')),
            ],
            options={
                'unique_together': {('barber', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('isApproved', models.BooleanField(verbose_name='Is Approved')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.barber')),
            ],
            options={
                'unique_together': {('barber', 'date', 'start_time')},
            },
        ),
    ]
