# Generated by Django 5.1.1 on 2024-10-01 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_barberschedule_day_of_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeoffrequest',
            options={'verbose_name': 'Time Off Request', 'verbose_name_plural': 'Time Off Requests'},
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('noShow', 'No Show'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.barber')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(help_text='The appointment associated with the selected service.', on_delete=django.db.models.deletion.CASCADE, to='api.booking', verbose_name='Booking Appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service', verbose_name='Service Name')),
            ],
            options={
                'verbose_name': 'Selected Service',
                'verbose_name_plural': 'Selected Services',
                'constraints': [models.UniqueConstraint(fields=('appointment', 'service'), name='unique_appointment_service')],
            },
        ),
    ]
