# Generated by Django 5.1.1 on 2024-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_timeoffrequest_options_booking_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='selectedservices',
            name='unique_appointment_service',
        ),
        migrations.AddConstraint(
            model_name='selectedservices',
            constraint=models.UniqueConstraint(fields=('appointment', 'service'), name='unique_appointment_service'),
        ),
    ]
