# Generated by Django 5.1.1 on 2024-10-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_selectedservices_unique_appointment_service_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectedServices',
            new_name='SelectedService',
        ),
    ]
