# Generated by Django 5.1.1 on 2024-10-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_selectedservices_selectedservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
    ]
