# Generated by Django 5.1.1 on 2024-10-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_booking_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
    ]
