# Generated by Django 5.1.1 on 2024-10-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_booking_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking Appointment', 'verbose_name_plural': 'Booking Appointments'},
        ),
    ]
