# Generated by Django 5.1.1 on 2024-10-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='isApproved',
            field=models.BooleanField(null=True, verbose_name='Is Approved'),
        ),
    ]
