# Generated by Django 5.1.1 on 2024-10-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_booking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='agreedMargin',
            field=models.PositiveIntegerField(default=60, help_text='Margin a barber earns from their earnings.', verbose_name="Barber's Margin."),
        ),
    ]
